module.exports={
    baseUrl:'http://localhost:3300/',
    //baseUrl:'http://48b88e29.ngrok.io',
    signUp:'user',
    login:'/login',
    signIn:'stud',
    upload:'file',
    attendance:'attendance'
};