module.exports={
    //baseUrl:'http://localhost:3000/',
    baseUrl:'http://b61490b3.ngrok.io/',
    signUp:'user',
    login:'/login',
    signIn:'stud',
    upload:'file',
    attendance:'attendance'
};